version: '2'
services:
    cooptit-app:
        image: cooptit
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://cooptit-postgresql:5432/cooptit
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://cooptit-elasticsearch:9200
        ports:
            - 8080:8080
    cooptit-postgresql:
        extends:
            file: postgresql.yml
            service: cooptit-postgresql
    cooptit-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: cooptit-elasticsearch
